/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/ic3/Documents/ros-ws/src/phx_uart_bridge/msg/MotorMessage.msg
 *
 */


#ifndef PHX_UART_BRIDGE_MESSAGE_MOTORMESSAGE_H
#define PHX_UART_BRIDGE_MESSAGE_MOTORMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phx_uart_bridge
{
template <class ContainerAllocator>
struct MotorMessage_
{
  typedef MotorMessage_<ContainerAllocator> Type;

  MotorMessage_()
    : motor0(0)
    , motor1(0)
    , motor2(0)
    , motor3(0)  {
    }
  MotorMessage_(const ContainerAllocator& _alloc)
    : motor0(0)
    , motor1(0)
    , motor2(0)
    , motor3(0)  {
    }



   typedef int16_t _motor0_type;
  _motor0_type motor0;

   typedef int16_t _motor1_type;
  _motor1_type motor1;

   typedef int16_t _motor2_type;
  _motor2_type motor2;

   typedef int16_t _motor3_type;
  _motor3_type motor3;




  typedef boost::shared_ptr< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> const> ConstPtr;

}; // struct MotorMessage_

typedef ::phx_uart_bridge::MotorMessage_<std::allocator<void> > MotorMessage;

typedef boost::shared_ptr< ::phx_uart_bridge::MotorMessage > MotorMessagePtr;
typedef boost::shared_ptr< ::phx_uart_bridge::MotorMessage const> MotorMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phx_uart_bridge::MotorMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phx_uart_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'phx_uart_bridge': ['/home/ic3/Documents/ros-ws/src/phx_uart_bridge/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "605d8d21e1e91da250972b12d398d70d";
  }

  static const char* value(const ::phx_uart_bridge::MotorMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x605d8d21e1e91da2ULL;
  static const uint64_t static_value2 = 0x50972b12d398d70dULL;
};

template<class ContainerAllocator>
struct DataType< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phx_uart_bridge/MotorMessage";
  }

  static const char* value(const ::phx_uart_bridge::MotorMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 motor0\n\
int16 motor1\n\
int16 motor2\n\
int16 motor3\n\
";
  }

  static const char* value(const ::phx_uart_bridge::MotorMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor0);
      stream.next(m.motor1);
      stream.next(m.motor2);
      stream.next(m.motor3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phx_uart_bridge::MotorMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phx_uart_bridge::MotorMessage_<ContainerAllocator>& v)
  {
    s << indent << "motor0: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor0);
    s << indent << "motor1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor1);
    s << indent << "motor2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor2);
    s << indent << "motor3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHX_UART_BRIDGE_MESSAGE_MOTORMESSAGE_H
