# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_v1.ui'
#
# Created: Sat Sep 26 17:25:53 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1302, 730)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1276, 661))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.left_tabs = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.left_tabs.setObjectName(_fromUtf8("left_tabs"))
        self.InfoPage = QtGui.QWidget()
        self.InfoPage.setObjectName(_fromUtf8("InfoPage"))
        self.verticalLayout_plots = QtGui.QVBoxLayout(self.InfoPage)
        self.verticalLayout_plots.setObjectName(_fromUtf8("verticalLayout_plots"))
        self.textBrowser = QtGui.QTextBrowser(self.InfoPage)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_plots.addWidget(self.textBrowser)
        self.left_tabs.addTab(self.InfoPage, _fromUtf8(""))
        self.gpsPage = QtGui.QWidget()
        self.gpsPage.setObjectName(_fromUtf8("gpsPage"))
        self.graphicsView_gps = PlotWidget(self.gpsPage)
        self.graphicsView_gps.setGeometry(QtCore.QRect(20, 20, 591, 491))
        self.graphicsView_gps.setObjectName(_fromUtf8("graphicsView_gps"))
        self.gps_label_reference_radius = QtGui.QLabel(self.gpsPage)
        self.gps_label_reference_radius.setGeometry(QtCore.QRect(450, 520, 161, 17))
        self.gps_label_reference_radius.setObjectName(_fromUtf8("gps_label_reference_radius"))
        self.left_tabs.addTab(self.gpsPage, _fromUtf8(""))
        self.ledPage = QtGui.QWidget()
        self.ledPage.setObjectName(_fromUtf8("ledPage"))
        self.gridLayoutWidget = QtGui.QWidget(self.ledPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 60, 251, 101))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_led_strip0 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_led_strip0.setMargin(0)
        self.gridLayout_led_strip0.setObjectName(_fromUtf8("gridLayout_led_strip0"))
        self.label_0_b = QtGui.QLabel(self.gridLayoutWidget)
        self.label_0_b.setObjectName(_fromUtf8("label_0_b"))
        self.gridLayout_led_strip0.addWidget(self.label_0_b, 2, 0, 1, 1)
        self.label_0_r = QtGui.QLabel(self.gridLayoutWidget)
        self.label_0_r.setObjectName(_fromUtf8("label_0_r"))
        self.gridLayout_led_strip0.addWidget(self.label_0_r, 0, 0, 1, 1)
        self.label_0_g = QtGui.QLabel(self.gridLayoutWidget)
        self.label_0_g.setObjectName(_fromUtf8("label_0_g"))
        self.gridLayout_led_strip0.addWidget(self.label_0_g, 1, 0, 1, 1)
        self.horizontalSlider_led_0_r = QtGui.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_led_0_r.setMaximum(255)
        self.horizontalSlider_led_0_r.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_0_r.setObjectName(_fromUtf8("horizontalSlider_led_0_r"))
        self.gridLayout_led_strip0.addWidget(self.horizontalSlider_led_0_r, 0, 1, 1, 1)
        self.horizontalSlider_led_0_g = QtGui.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_led_0_g.setMaximum(255)
        self.horizontalSlider_led_0_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_0_g.setObjectName(_fromUtf8("horizontalSlider_led_0_g"))
        self.gridLayout_led_strip0.addWidget(self.horizontalSlider_led_0_g, 1, 1, 1, 1)
        self.horizontalSlider_led_0_b = QtGui.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_led_0_b.setMaximum(255)
        self.horizontalSlider_led_0_b.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_0_b.setObjectName(_fromUtf8("horizontalSlider_led_0_b"))
        self.gridLayout_led_strip0.addWidget(self.horizontalSlider_led_0_b, 2, 1, 1, 1)
        self.led_label_strip_0 = QtGui.QLabel(self.ledPage)
        self.led_label_strip_0.setGeometry(QtCore.QRect(80, 40, 91, 17))
        self.led_label_strip_0.setObjectName(_fromUtf8("led_label_strip_0"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.ledPage)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(350, 60, 251, 101))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_led_strip1 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_led_strip1.setMargin(0)
        self.gridLayout_led_strip1.setObjectName(_fromUtf8("gridLayout_led_strip1"))
        self.label_1_r = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_1_r.setObjectName(_fromUtf8("label_1_r"))
        self.gridLayout_led_strip1.addWidget(self.label_1_r, 0, 0, 1, 1)
        self.label_1_g = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_1_g.setObjectName(_fromUtf8("label_1_g"))
        self.gridLayout_led_strip1.addWidget(self.label_1_g, 1, 0, 1, 1)
        self.horizontalSlider_led_1_r = QtGui.QSlider(self.gridLayoutWidget_2)
        self.horizontalSlider_led_1_r.setMaximum(255)
        self.horizontalSlider_led_1_r.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_1_r.setObjectName(_fromUtf8("horizontalSlider_led_1_r"))
        self.gridLayout_led_strip1.addWidget(self.horizontalSlider_led_1_r, 0, 1, 1, 1)
        self.horizontalSlider_led_1_g = QtGui.QSlider(self.gridLayoutWidget_2)
        self.horizontalSlider_led_1_g.setMaximum(255)
        self.horizontalSlider_led_1_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_1_g.setObjectName(_fromUtf8("horizontalSlider_led_1_g"))
        self.gridLayout_led_strip1.addWidget(self.horizontalSlider_led_1_g, 1, 1, 1, 1)
        self.horizontalSlider_led_1_b = QtGui.QSlider(self.gridLayoutWidget_2)
        self.horizontalSlider_led_1_b.setMaximum(255)
        self.horizontalSlider_led_1_b.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_1_b.setObjectName(_fromUtf8("horizontalSlider_led_1_b"))
        self.gridLayout_led_strip1.addWidget(self.horizontalSlider_led_1_b, 2, 1, 1, 1)
        self.label_1_b = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_1_b.setObjectName(_fromUtf8("label_1_b"))
        self.gridLayout_led_strip1.addWidget(self.label_1_b, 2, 0, 1, 1)
        self.led_label_strip_1 = QtGui.QLabel(self.ledPage)
        self.led_label_strip_1.setGeometry(QtCore.QRect(360, 40, 91, 17))
        self.led_label_strip_1.setObjectName(_fromUtf8("led_label_strip_1"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.ledPage)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(70, 200, 251, 101))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_led_strip2 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_led_strip2.setMargin(0)
        self.gridLayout_led_strip2.setObjectName(_fromUtf8("gridLayout_led_strip2"))
        self.label_2_b = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_2_b.setObjectName(_fromUtf8("label_2_b"))
        self.gridLayout_led_strip2.addWidget(self.label_2_b, 2, 0, 1, 1)
        self.label_2_r = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_2_r.setObjectName(_fromUtf8("label_2_r"))
        self.gridLayout_led_strip2.addWidget(self.label_2_r, 0, 0, 1, 1)
        self.label_2_g = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_2_g.setObjectName(_fromUtf8("label_2_g"))
        self.gridLayout_led_strip2.addWidget(self.label_2_g, 1, 0, 1, 1)
        self.horizontalSlider_led_2_r = QtGui.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlider_led_2_r.setMaximum(255)
        self.horizontalSlider_led_2_r.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_2_r.setObjectName(_fromUtf8("horizontalSlider_led_2_r"))
        self.gridLayout_led_strip2.addWidget(self.horizontalSlider_led_2_r, 0, 1, 1, 1)
        self.horizontalSlider_led_2_g = QtGui.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlider_led_2_g.setMaximum(255)
        self.horizontalSlider_led_2_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_2_g.setObjectName(_fromUtf8("horizontalSlider_led_2_g"))
        self.gridLayout_led_strip2.addWidget(self.horizontalSlider_led_2_g, 1, 1, 1, 1)
        self.horizontalSlider_led_2_b = QtGui.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlider_led_2_b.setMaximum(255)
        self.horizontalSlider_led_2_b.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_2_b.setObjectName(_fromUtf8("horizontalSlider_led_2_b"))
        self.gridLayout_led_strip2.addWidget(self.horizontalSlider_led_2_b, 2, 1, 1, 1)
        self.led_label_strip_2 = QtGui.QLabel(self.ledPage)
        self.led_label_strip_2.setGeometry(QtCore.QRect(80, 180, 91, 17))
        self.led_label_strip_2.setObjectName(_fromUtf8("led_label_strip_2"))
        self.led_label_strip_3 = QtGui.QLabel(self.ledPage)
        self.led_label_strip_3.setGeometry(QtCore.QRect(360, 180, 91, 17))
        self.led_label_strip_3.setObjectName(_fromUtf8("led_label_strip_3"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.ledPage)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(350, 200, 251, 101))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_led_strip3 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_led_strip3.setMargin(0)
        self.gridLayout_led_strip3.setObjectName(_fromUtf8("gridLayout_led_strip3"))
        self.label__3_b = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label__3_b.setObjectName(_fromUtf8("label__3_b"))
        self.gridLayout_led_strip3.addWidget(self.label__3_b, 2, 0, 1, 1)
        self.label_3_r = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_3_r.setObjectName(_fromUtf8("label_3_r"))
        self.gridLayout_led_strip3.addWidget(self.label_3_r, 0, 0, 1, 1)
        self.label_3_g = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_3_g.setObjectName(_fromUtf8("label_3_g"))
        self.gridLayout_led_strip3.addWidget(self.label_3_g, 1, 0, 1, 1)
        self.horizontalSlider_led_3_r = QtGui.QSlider(self.gridLayoutWidget_4)
        self.horizontalSlider_led_3_r.setMaximum(255)
        self.horizontalSlider_led_3_r.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_3_r.setObjectName(_fromUtf8("horizontalSlider_led_3_r"))
        self.gridLayout_led_strip3.addWidget(self.horizontalSlider_led_3_r, 0, 1, 1, 1)
        self.horizontalSlider_led_3_g = QtGui.QSlider(self.gridLayoutWidget_4)
        self.horizontalSlider_led_3_g.setMaximum(255)
        self.horizontalSlider_led_3_g.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_3_g.setObjectName(_fromUtf8("horizontalSlider_led_3_g"))
        self.gridLayout_led_strip3.addWidget(self.horizontalSlider_led_3_g, 1, 1, 1, 1)
        self.horizontalSlider_led_3_b = QtGui.QSlider(self.gridLayoutWidget_4)
        self.horizontalSlider_led_3_b.setMaximum(255)
        self.horizontalSlider_led_3_b.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_led_3_b.setObjectName(_fromUtf8("horizontalSlider_led_3_b"))
        self.gridLayout_led_strip3.addWidget(self.horizontalSlider_led_3_b, 2, 1, 1, 1)
        self.pushButton_led_strip_update = QtGui.QPushButton(self.ledPage)
        self.pushButton_led_strip_update.setGeometry(QtCore.QRect(470, 320, 131, 27))
        self.pushButton_led_strip_update.setObjectName(_fromUtf8("pushButton_led_strip_update"))
        self.checkBox_led_strip_update_continuous = QtGui.QCheckBox(self.ledPage)
        self.checkBox_led_strip_update_continuous.setGeometry(QtCore.QRect(320, 320, 131, 31))
        self.checkBox_led_strip_update_continuous.setObjectName(_fromUtf8("checkBox_led_strip_update_continuous"))
        self.left_tabs.addTab(self.ledPage, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.left_tabs)
        self.right_tabs = QtGui.QTabWidget(self.horizontalLayoutWidget)
        self.right_tabs.setObjectName(_fromUtf8("right_tabs"))
        self.parameter_tab = QtGui.QWidget()
        self.parameter_tab.setObjectName(_fromUtf8("parameter_tab"))
        self.layoutWidget = QtGui.QWidget(self.parameter_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 566))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_parameters = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_parameters.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_parameters.setMargin(0)
        self.gridLayout_parameters.setObjectName(_fromUtf8("gridLayout_parameters"))
        self.lcdNumber_parameter_00 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_00.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_00.setObjectName(_fromUtf8("lcdNumber_parameter_00"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_00, 0, 1, 1, 1)
        self.label_parameter_10 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_10.setObjectName(_fromUtf8("label_parameter_10"))
        self.gridLayout_parameters.addWidget(self.label_parameter_10, 10, 2, 1, 1)
        self.lcdNumber_parameter_16 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_16.setObjectName(_fromUtf8("lcdNumber_parameter_16"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_16, 16, 1, 1, 1)
        self.lcdNumber_parameter_06 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_06.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_06.setObjectName(_fromUtf8("lcdNumber_parameter_06"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_06, 6, 1, 1, 1)
        self.horizontalSlider_parameter_10 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_10.setObjectName(_fromUtf8("horizontalSlider_parameter_10"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_10, 10, 0, 1, 1)
        self.horizontalSlider_parameter_15 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_15.setObjectName(_fromUtf8("horizontalSlider_parameter_15"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_15, 15, 0, 1, 1)
        self.horizontalSlider_parameter_03 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_03.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_03.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_03.setObjectName(_fromUtf8("horizontalSlider_parameter_03"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_03, 3, 0, 1, 1)
        self.lcdNumber_parameter_01 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_01.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_01.setObjectName(_fromUtf8("lcdNumber_parameter_01"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_01, 1, 1, 1, 1)
        self.lcdNumber_parameter_03 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_03.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_03.setObjectName(_fromUtf8("lcdNumber_parameter_03"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_03, 3, 1, 1, 1)
        self.horizontalSlider_parameter_05 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_05.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_05.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_05.setObjectName(_fromUtf8("horizontalSlider_parameter_05"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_05, 5, 0, 1, 1)
        self.label_parameter_00 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_00.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_00.setObjectName(_fromUtf8("label_parameter_00"))
        self.gridLayout_parameters.addWidget(self.label_parameter_00, 0, 2, 1, 1)
        self.label_parameter_15 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_15.setObjectName(_fromUtf8("label_parameter_15"))
        self.gridLayout_parameters.addWidget(self.label_parameter_15, 15, 2, 1, 1)
        self.horizontalSlider_parameter_01 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_01.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_01.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_01.setObjectName(_fromUtf8("horizontalSlider_parameter_01"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_01, 1, 0, 1, 1)
        self.label_parameter_03 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_03.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_03.setObjectName(_fromUtf8("label_parameter_03"))
        self.gridLayout_parameters.addWidget(self.label_parameter_03, 3, 2, 1, 1)
        self.label_parameter_01 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_01.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_01.setObjectName(_fromUtf8("label_parameter_01"))
        self.gridLayout_parameters.addWidget(self.label_parameter_01, 1, 2, 1, 1)
        self.horizontalSlider_parameter_00 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_00.setMaximumSize(QtCore.QSize(1000, 20))
        self.horizontalSlider_parameter_00.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_00.setObjectName(_fromUtf8("horizontalSlider_parameter_00"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_00, 0, 0, 1, 1)
        self.horizontalSlider_parameter_07 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_07.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_07.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_07.setObjectName(_fromUtf8("horizontalSlider_parameter_07"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_07, 7, 0, 1, 1)
        self.horizontalSlider_parameter_02 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_02.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_02.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_02.setObjectName(_fromUtf8("horizontalSlider_parameter_02"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_02, 2, 0, 1, 1)
        self.label_parameter_04 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_04.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_04.setObjectName(_fromUtf8("label_parameter_04"))
        self.gridLayout_parameters.addWidget(self.label_parameter_04, 4, 2, 1, 1)
        self.horizontalSlider_parameter_04 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_04.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_04.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_04.setObjectName(_fromUtf8("horizontalSlider_parameter_04"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_04, 4, 0, 1, 1)
        self.label_parameter_11 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_11.setObjectName(_fromUtf8("label_parameter_11"))
        self.gridLayout_parameters.addWidget(self.label_parameter_11, 11, 2, 1, 1)
        self.horizontalSlider_parameter_12 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_12.setObjectName(_fromUtf8("horizontalSlider_parameter_12"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_12, 12, 0, 1, 1)
        self.horizontalSlider_parameter_16 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_16.setObjectName(_fromUtf8("horizontalSlider_parameter_16"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_16, 16, 0, 1, 1)
        self.label_parameter_06 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_06.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_06.setObjectName(_fromUtf8("label_parameter_06"))
        self.gridLayout_parameters.addWidget(self.label_parameter_06, 6, 2, 1, 1)
        self.horizontalSlider_parameter_06 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_06.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_06.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_06.setObjectName(_fromUtf8("horizontalSlider_parameter_06"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_06, 6, 0, 1, 1)
        self.label_parameter_07 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_07.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_07.setObjectName(_fromUtf8("label_parameter_07"))
        self.gridLayout_parameters.addWidget(self.label_parameter_07, 7, 2, 1, 1)
        self.lcdNumber_parameter_02 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_02.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_02.setObjectName(_fromUtf8("lcdNumber_parameter_02"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_02, 2, 1, 1, 1)
        self.label_parameter_02 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_02.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_02.setObjectName(_fromUtf8("label_parameter_02"))
        self.gridLayout_parameters.addWidget(self.label_parameter_02, 2, 2, 1, 1)
        self.lcdNumber_parameter_04 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_04.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_04.setObjectName(_fromUtf8("lcdNumber_parameter_04"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_04, 4, 1, 1, 1)
        self.lcdNumber_parameter_07 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_07.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_07.setObjectName(_fromUtf8("lcdNumber_parameter_07"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_07, 7, 1, 1, 1)
        self.lcdNumber_parameter_05 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_05.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_05.setObjectName(_fromUtf8("lcdNumber_parameter_05"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_05, 5, 1, 1, 1)
        self.label_parameter_05 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_05.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_05.setObjectName(_fromUtf8("label_parameter_05"))
        self.gridLayout_parameters.addWidget(self.label_parameter_05, 5, 2, 1, 1)
        self.horizontalSlider_parameter_08 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_08.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_08.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_08.setObjectName(_fromUtf8("horizontalSlider_parameter_08"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_08, 8, 0, 1, 1)
        self.label_parameter_09 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_09.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_09.setObjectName(_fromUtf8("label_parameter_09"))
        self.gridLayout_parameters.addWidget(self.label_parameter_09, 9, 2, 1, 1)
        self.label_parameter_08 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_08.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_08.setObjectName(_fromUtf8("label_parameter_08"))
        self.gridLayout_parameters.addWidget(self.label_parameter_08, 8, 2, 1, 1)
        self.horizontalSlider_parameter_13 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_13.setObjectName(_fromUtf8("horizontalSlider_parameter_13"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_13, 13, 0, 1, 1)
        self.label_parameter_13 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_13.setObjectName(_fromUtf8("label_parameter_13"))
        self.gridLayout_parameters.addWidget(self.label_parameter_13, 13, 2, 1, 1)
        self.horizontalSlider_parameter_11 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_11.setObjectName(_fromUtf8("horizontalSlider_parameter_11"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_11, 11, 0, 1, 1)
        self.label_parameter_14 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_14.setObjectName(_fromUtf8("label_parameter_14"))
        self.gridLayout_parameters.addWidget(self.label_parameter_14, 14, 2, 1, 1)
        self.label_parameter_12 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_12.setObjectName(_fromUtf8("label_parameter_12"))
        self.gridLayout_parameters.addWidget(self.label_parameter_12, 12, 2, 1, 1)
        self.horizontalSlider_parameter_14 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_14.setObjectName(_fromUtf8("horizontalSlider_parameter_14"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_14, 14, 0, 1, 1)
        self.horizontalSlider_parameter_09 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_09.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_09.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_09.setObjectName(_fromUtf8("horizontalSlider_parameter_09"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_09, 9, 0, 1, 1)
        self.horizontalSlider_parameter_17 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_parameter_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_parameter_17.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_parameter_17.setObjectName(_fromUtf8("horizontalSlider_parameter_17"))
        self.gridLayout_parameters.addWidget(self.horizontalSlider_parameter_17, 17, 0, 1, 1)
        self.label_parameter_16 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_16.setObjectName(_fromUtf8("label_parameter_16"))
        self.gridLayout_parameters.addWidget(self.label_parameter_16, 16, 2, 1, 1)
        self.label_parameter_17 = QtGui.QLabel(self.layoutWidget)
        self.label_parameter_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_parameter_17.setObjectName(_fromUtf8("label_parameter_17"))
        self.gridLayout_parameters.addWidget(self.label_parameter_17, 17, 2, 1, 1)
        self.lcdNumber_parameter_08 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_08.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_08.setObjectName(_fromUtf8("lcdNumber_parameter_08"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_08, 8, 1, 1, 1)
        self.lcdNumber_parameter_09 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_09.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_09.setObjectName(_fromUtf8("lcdNumber_parameter_09"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_09, 9, 1, 1, 1)
        self.lcdNumber_parameter_10 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_10.setObjectName(_fromUtf8("lcdNumber_parameter_10"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_10, 10, 1, 1, 1)
        self.lcdNumber_parameter_11 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_11.setObjectName(_fromUtf8("lcdNumber_parameter_11"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_11, 11, 1, 1, 1)
        self.lcdNumber_parameter_12 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_12.setObjectName(_fromUtf8("lcdNumber_parameter_12"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_12, 12, 1, 1, 1)
        self.lcdNumber_parameter_13 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_13.setObjectName(_fromUtf8("lcdNumber_parameter_13"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_13, 13, 1, 1, 1)
        self.lcdNumber_parameter_14 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_14.setObjectName(_fromUtf8("lcdNumber_parameter_14"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_14, 14, 1, 1, 1)
        self.lcdNumber_parameter_15 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_15.setObjectName(_fromUtf8("lcdNumber_parameter_15"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_15, 15, 1, 1, 1)
        self.lcdNumber_parameter_17 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_parameter_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lcdNumber_parameter_17.setObjectName(_fromUtf8("lcdNumber_parameter_17"))
        self.gridLayout_parameters.addWidget(self.lcdNumber_parameter_17, 17, 1, 1, 1)
        self.checkBox_parameters_update_continuous = QtGui.QCheckBox(self.parameter_tab)
        self.checkBox_parameters_update_continuous.setGeometry(QtCore.QRect(300, 590, 131, 22))
        self.checkBox_parameters_update_continuous.setObjectName(_fromUtf8("checkBox_parameters_update_continuous"))
        self.pushButton_parameters_update = QtGui.QPushButton(self.parameter_tab)
        self.pushButton_parameters_update.setGeometry(QtCore.QRect(480, 590, 131, 27))
        self.pushButton_parameters_update.setObjectName(_fromUtf8("pushButton_parameters_update"))
        self.right_tabs.addTab(self.parameter_tab, _fromUtf8(""))
        self.rc_fc = QtGui.QWidget()
        self.rc_fc.setObjectName(_fromUtf8("rc_fc"))
        self.remote_slider_rc_fc_throttle = QtGui.QSlider(self.rc_fc)
        self.remote_slider_rc_fc_throttle.setGeometry(QtCore.QRect(100, 70, 22, 160))
        self.remote_slider_rc_fc_throttle.setMinimum(1000)
        self.remote_slider_rc_fc_throttle.setMaximum(2000)
        self.remote_slider_rc_fc_throttle.setProperty("value", 1000)
        self.remote_slider_rc_fc_throttle.setOrientation(QtCore.Qt.Vertical)
        self.remote_slider_rc_fc_throttle.setTickPosition(QtGui.QSlider.NoTicks)
        self.remote_slider_rc_fc_throttle.setObjectName(_fromUtf8("remote_slider_rc_fc_throttle"))
        self.remote_slider_rc_fc_yaw = QtGui.QSlider(self.rc_fc)
        self.remote_slider_rc_fc_yaw.setGeometry(QtCore.QRect(30, 140, 160, 22))
        self.remote_slider_rc_fc_yaw.setMinimum(1000)
        self.remote_slider_rc_fc_yaw.setMaximum(2000)
        self.remote_slider_rc_fc_yaw.setOrientation(QtCore.Qt.Horizontal)
        self.remote_slider_rc_fc_yaw.setTickPosition(QtGui.QSlider.NoTicks)
        self.remote_slider_rc_fc_yaw.setObjectName(_fromUtf8("remote_slider_rc_fc_yaw"))
        self.remote_slider_rc_fc_pitch = QtGui.QSlider(self.rc_fc)
        self.remote_slider_rc_fc_pitch.setGeometry(QtCore.QRect(300, 70, 22, 160))
        self.remote_slider_rc_fc_pitch.setMinimum(1000)
        self.remote_slider_rc_fc_pitch.setMaximum(2000)
        self.remote_slider_rc_fc_pitch.setOrientation(QtCore.Qt.Vertical)
        self.remote_slider_rc_fc_pitch.setTickPosition(QtGui.QSlider.NoTicks)
        self.remote_slider_rc_fc_pitch.setObjectName(_fromUtf8("remote_slider_rc_fc_pitch"))
        self.remote_slider_rc_fc_roll = QtGui.QSlider(self.rc_fc)
        self.remote_slider_rc_fc_roll.setGeometry(QtCore.QRect(230, 140, 160, 22))
        self.remote_slider_rc_fc_roll.setMinimum(1000)
        self.remote_slider_rc_fc_roll.setMaximum(2000)
        self.remote_slider_rc_fc_roll.setOrientation(QtCore.Qt.Horizontal)
        self.remote_slider_rc_fc_roll.setTickPosition(QtGui.QSlider.NoTicks)
        self.remote_slider_rc_fc_roll.setObjectName(_fromUtf8("remote_slider_rc_fc_roll"))
        self.graphicsView_rc_fc = PlotWidget(self.rc_fc)
        self.graphicsView_rc_fc.setGeometry(QtCore.QRect(10, 260, 601, 361))
        self.graphicsView_rc_fc.setObjectName(_fromUtf8("graphicsView_rc_fc"))
        self.rc_fc_label_headline = QtGui.QLabel(self.rc_fc)
        self.rc_fc_label_headline.setGeometry(QtCore.QRect(40, 20, 171, 16))
        self.rc_fc_label_headline.setObjectName(_fromUtf8("rc_fc_label_headline"))
        self.rc_fc_label_throttle = QtGui.QLabel(self.rc_fc)
        self.rc_fc_label_throttle.setGeometry(QtCore.QRect(120, 70, 66, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_throttle.setFont(font)
        self.rc_fc_label_throttle.setStyleSheet(_fromUtf8("QLabel{ color: rgb(0,200,0) }"))
        self.rc_fc_label_throttle.setObjectName(_fromUtf8("rc_fc_label_throttle"))
        self.rc_fc_label_yaw = QtGui.QLabel(self.rc_fc)
        self.rc_fc_label_yaw.setGeometry(QtCore.QRect(160, 160, 31, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_yaw.setFont(font)
        self.rc_fc_label_yaw.setStyleSheet(_fromUtf8("QLabel{ color: rgb(0,0,250) }"))
        self.rc_fc_label_yaw.setObjectName(_fromUtf8("rc_fc_label_yaw"))
        self.rc_fc_label_pitch = QtGui.QLabel(self.rc_fc)
        self.rc_fc_label_pitch.setGeometry(QtCore.QRect(320, 70, 66, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_pitch.setFont(font)
        self.rc_fc_label_pitch.setStyleSheet(_fromUtf8("QLabel{ color: rgb(250,0,250) }"))
        self.rc_fc_label_pitch.setObjectName(_fromUtf8("rc_fc_label_pitch"))
        self.rc_fc_label_roll = QtGui.QLabel(self.rc_fc)
        self.rc_fc_label_roll.setGeometry(QtCore.QRect(370, 160, 41, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_roll.setFont(font)
        self.rc_fc_label_roll.setStyleSheet(_fromUtf8("QLabel{ color: rgb(255,0,0) }"))
        self.rc_fc_label_roll.setObjectName(_fromUtf8("rc_fc_label_roll"))
        self.rc_fc_label_gps_home = QtGui.QLabel(self.rc_fc)
        self.rc_fc_label_gps_home.setGeometry(QtCore.QRect(420, 70, 41, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_gps_home.setFont(font)
        self.rc_fc_label_gps_home.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_gps_home.setObjectName(_fromUtf8("rc_fc_label_gps_home"))
        self.rc_fc_label_gps_3 = QtGui.QLabel(self.rc_fc)
        self.rc_fc_label_gps_3.setGeometry(QtCore.QRect(430, 140, 31, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_gps_3.setFont(font)
        self.rc_fc_label_gps_3.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_gps_3.setObjectName(_fromUtf8("rc_fc_label_gps_3"))
        self.line_separator_rc_fc_0 = QtGui.QFrame(self.rc_fc)
        self.line_separator_rc_fc_0.setGeometry(QtCore.QRect(7, 40, 611, 20))
        self.line_separator_rc_fc_0.setFrameShape(QtGui.QFrame.HLine)
        self.line_separator_rc_fc_0.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_separator_rc_fc_0.setObjectName(_fromUtf8("line_separator_rc_fc_0"))
        self.line_separator_rc_fc_1 = QtGui.QFrame(self.rc_fc)
        self.line_separator_rc_fc_1.setGeometry(QtCore.QRect(400, 50, 20, 201))
        self.line_separator_rc_fc_1.setFrameShape(QtGui.QFrame.VLine)
        self.line_separator_rc_fc_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_separator_rc_fc_1.setObjectName(_fromUtf8("line_separator_rc_fc_1"))
        self.line_separator_rc_fc_2 = QtGui.QFrame(self.rc_fc)
        self.line_separator_rc_fc_2.setGeometry(QtCore.QRect(200, 50, 20, 201))
        self.line_separator_rc_fc_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_separator_rc_fc_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_separator_rc_fc_2.setObjectName(_fromUtf8("line_separator_rc_fc_2"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.rc_fc)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(460, 50, 160, 201))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_aux_rc_fc = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_aux_rc_fc.setMargin(0)
        self.gridLayout_aux_rc_fc.setObjectName(_fromUtf8("gridLayout_aux_rc_fc"))
        self.remote_slider_rc_fc_aux3 = QtGui.QSlider(self.gridLayoutWidget_5)
        self.remote_slider_rc_fc_aux3.setMinimum(1000)
        self.remote_slider_rc_fc_aux3.setMaximum(2000)
        self.remote_slider_rc_fc_aux3.setOrientation(QtCore.Qt.Vertical)
        self.remote_slider_rc_fc_aux3.setObjectName(_fromUtf8("remote_slider_rc_fc_aux3"))
        self.gridLayout_aux_rc_fc.addWidget(self.remote_slider_rc_fc_aux3, 1, 2, 1, 1)
        self.rc_fc_label_mag = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_mag.setFont(font)
        self.rc_fc_label_mag.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_mag.setObjectName(_fromUtf8("rc_fc_label_mag"))
        self.gridLayout_aux_rc_fc.addWidget(self.rc_fc_label_mag, 0, 2, 1, 1)
        self.remote_slider_rc_fc_aux1 = QtGui.QSlider(self.gridLayoutWidget_5)
        self.remote_slider_rc_fc_aux1.setMinimum(1000)
        self.remote_slider_rc_fc_aux1.setMaximum(2000)
        self.remote_slider_rc_fc_aux1.setOrientation(QtCore.Qt.Vertical)
        self.remote_slider_rc_fc_aux1.setObjectName(_fromUtf8("remote_slider_rc_fc_aux1"))
        self.gridLayout_aux_rc_fc.addWidget(self.remote_slider_rc_fc_aux1, 1, 0, 1, 1)
        self.rc_fc_label_gps = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_gps.setFont(font)
        self.rc_fc_label_gps.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_gps.setObjectName(_fromUtf8("rc_fc_label_gps"))
        self.gridLayout_aux_rc_fc.addWidget(self.rc_fc_label_gps, 0, 0, 1, 1)
        self.remote_slider_rc_fc_aux4 = QtGui.QSlider(self.gridLayoutWidget_5)
        self.remote_slider_rc_fc_aux4.setMinimum(1000)
        self.remote_slider_rc_fc_aux4.setMaximum(2000)
        self.remote_slider_rc_fc_aux4.setOrientation(QtCore.Qt.Vertical)
        self.remote_slider_rc_fc_aux4.setObjectName(_fromUtf8("remote_slider_rc_fc_aux4"))
        self.gridLayout_aux_rc_fc.addWidget(self.remote_slider_rc_fc_aux4, 1, 3, 1, 1)
        self.remote_slider_rc_fc_aux2 = QtGui.QSlider(self.gridLayoutWidget_5)
        self.remote_slider_rc_fc_aux2.setMinimum(1000)
        self.remote_slider_rc_fc_aux2.setMaximum(2000)
        self.remote_slider_rc_fc_aux2.setOrientation(QtCore.Qt.Vertical)
        self.remote_slider_rc_fc_aux2.setObjectName(_fromUtf8("remote_slider_rc_fc_aux2"))
        self.gridLayout_aux_rc_fc.addWidget(self.remote_slider_rc_fc_aux2, 1, 1, 1, 1)
        self.rc_fc_label_baro = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_baro.setFont(font)
        self.rc_fc_label_baro.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_baro.setObjectName(_fromUtf8("rc_fc_label_baro"))
        self.gridLayout_aux_rc_fc.addWidget(self.rc_fc_label_baro, 0, 3, 1, 1)
        self.rc_fc_label_aux1 = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_aux1.setFont(font)
        self.rc_fc_label_aux1.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_aux1.setObjectName(_fromUtf8("rc_fc_label_aux1"))
        self.gridLayout_aux_rc_fc.addWidget(self.rc_fc_label_aux1, 2, 0, 1, 1)
        self.rc_fc_label_aux1_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_aux1_2.setFont(font)
        self.rc_fc_label_aux1_2.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_aux1_2.setObjectName(_fromUtf8("rc_fc_label_aux1_2"))
        self.gridLayout_aux_rc_fc.addWidget(self.rc_fc_label_aux1_2, 2, 1, 1, 1)
        self.rc_fc_label_aux1_3 = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_aux1_3.setFont(font)
        self.rc_fc_label_aux1_3.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_aux1_3.setObjectName(_fromUtf8("rc_fc_label_aux1_3"))
        self.gridLayout_aux_rc_fc.addWidget(self.rc_fc_label_aux1_3, 2, 2, 1, 1)
        self.rc_fc_label_aux1_4 = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rc_fc_label_aux1_4.setFont(font)
        self.rc_fc_label_aux1_4.setStyleSheet(_fromUtf8(""))
        self.rc_fc_label_aux1_4.setObjectName(_fromUtf8("rc_fc_label_aux1_4"))
        self.gridLayout_aux_rc_fc.addWidget(self.rc_fc_label_aux1_4, 2, 3, 1, 1)
        self.rc_fc_label_read_only = QtGui.QLabel(self.rc_fc)
        self.rc_fc_label_read_only.setGeometry(QtCore.QRect(530, 20, 91, 17))
        self.rc_fc_label_read_only.setObjectName(_fromUtf8("rc_fc_label_read_only"))
        self.lcdNumber_rc_fc_throttle = QtGui.QLCDNumber(self.rc_fc)
        self.lcdNumber_rc_fc_throttle.setGeometry(QtCore.QRect(130, 90, 64, 23))
        self.lcdNumber_rc_fc_throttle.setNumDigits(5)
        self.lcdNumber_rc_fc_throttle.setObjectName(_fromUtf8("lcdNumber_rc_fc_throttle"))
        self.lcdNumber_rc_fc_yaw = QtGui.QLCDNumber(self.rc_fc)
        self.lcdNumber_rc_fc_yaw.setGeometry(QtCore.QRect(130, 180, 64, 23))
        self.lcdNumber_rc_fc_yaw.setObjectName(_fromUtf8("lcdNumber_rc_fc_yaw"))
        self.lcdNumber_rc_fc_roll = QtGui.QLCDNumber(self.rc_fc)
        self.lcdNumber_rc_fc_roll.setGeometry(QtCore.QRect(330, 180, 64, 23))
        self.lcdNumber_rc_fc_roll.setObjectName(_fromUtf8("lcdNumber_rc_fc_roll"))
        self.lcdNumber_rc_fc_pitch = QtGui.QLCDNumber(self.rc_fc)
        self.lcdNumber_rc_fc_pitch.setGeometry(QtCore.QRect(330, 90, 64, 23))
        self.lcdNumber_rc_fc_pitch.setObjectName(_fromUtf8("lcdNumber_rc_fc_pitch"))
        self.right_tabs.addTab(self.rc_fc, _fromUtf8(""))
        self.altitude_tab = QtGui.QWidget()
        self.altitude_tab.setObjectName(_fromUtf8("altitude_tab"))
        self.graphicsView_altitude = PlotWidget(self.altitude_tab)
        self.graphicsView_altitude.setGeometry(QtCore.QRect(20, 10, 461, 371))
        self.graphicsView_altitude.setObjectName(_fromUtf8("graphicsView_altitude"))
        self.slider_altitude = QtGui.QSlider(self.altitude_tab)
        self.slider_altitude.setGeometry(QtCore.QRect(540, 10, 22, 371))
        self.slider_altitude.setOrientation(QtCore.Qt.Vertical)
        self.slider_altitude.setObjectName(_fromUtf8("slider_altitude"))
        self.right_tabs.addTab(self.altitude_tab, _fromUtf8(""))
        self.video_tab = QtGui.QWidget()
        self.video_tab.setObjectName(_fromUtf8("video_tab"))
        self.checkBox = QtGui.QCheckBox(self.video_tab)
        self.checkBox.setGeometry(QtCore.QRect(390, 30, 201, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.right_tabs.addTab(self.video_tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.right_tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.left_tabs.setCurrentIndex(2)
        self.right_tabs.setCurrentIndex(1)
        QtCore.QObject.connect(self.remote_slider_rc_fc_throttle, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_rc_fc_throttle.display)
        QtCore.QObject.connect(self.remote_slider_rc_fc_yaw, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_rc_fc_yaw.display)
        QtCore.QObject.connect(self.remote_slider_rc_fc_pitch, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_rc_fc_pitch.display)
        QtCore.QObject.connect(self.remote_slider_rc_fc_roll, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_rc_fc_roll.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "phoenixGUI", None))
        self.left_tabs.setTabText(self.left_tabs.indexOf(self.InfoPage), _translate("MainWindow", "info", None))
        self.gps_label_reference_radius.setText(_translate("MainWindow", "reference diameter 5m", None))
        self.left_tabs.setTabText(self.left_tabs.indexOf(self.gpsPage), _translate("MainWindow", "gps", None))
        self.label_0_b.setText(_translate("MainWindow", "blue", None))
        self.label_0_r.setText(_translate("MainWindow", "red", None))
        self.label_0_g.setText(_translate("MainWindow", "green", None))
        self.led_label_strip_0.setText(_translate("MainWindow", "LED strip 0", None))
        self.label_1_r.setText(_translate("MainWindow", "red", None))
        self.label_1_g.setText(_translate("MainWindow", "green", None))
        self.label_1_b.setText(_translate("MainWindow", "blue", None))
        self.led_label_strip_1.setText(_translate("MainWindow", "LED strip 1", None))
        self.label_2_b.setText(_translate("MainWindow", "blue", None))
        self.label_2_r.setText(_translate("MainWindow", "red", None))
        self.label_2_g.setText(_translate("MainWindow", "green", None))
        self.led_label_strip_2.setText(_translate("MainWindow", "LED strip 2", None))
        self.led_label_strip_3.setText(_translate("MainWindow", "LED strip 3", None))
        self.label__3_b.setText(_translate("MainWindow", "blue", None))
        self.label_3_r.setText(_translate("MainWindow", "red", None))
        self.label_3_g.setText(_translate("MainWindow", "green", None))
        self.pushButton_led_strip_update.setText(_translate("MainWindow", "update LED strips", None))
        self.checkBox_led_strip_update_continuous.setText(_translate("MainWindow", "continuous", None))
        self.left_tabs.setTabText(self.left_tabs.indexOf(self.ledPage), _translate("MainWindow", "led", None))
        self.label_parameter_10.setText(_translate("MainWindow", "parameter10", None))
        self.label_parameter_00.setText(_translate("MainWindow", "parameter0", None))
        self.label_parameter_15.setText(_translate("MainWindow", "parameter15", None))
        self.label_parameter_03.setText(_translate("MainWindow", "parameter3", None))
        self.label_parameter_01.setText(_translate("MainWindow", "parameter1", None))
        self.label_parameter_04.setText(_translate("MainWindow", "parameter4", None))
        self.label_parameter_11.setText(_translate("MainWindow", "parameter11", None))
        self.label_parameter_06.setText(_translate("MainWindow", "parameter6", None))
        self.label_parameter_07.setText(_translate("MainWindow", "parameter7", None))
        self.label_parameter_02.setText(_translate("MainWindow", "parameter2", None))
        self.label_parameter_05.setText(_translate("MainWindow", "parameter5", None))
        self.label_parameter_09.setText(_translate("MainWindow", "parameter9", None))
        self.label_parameter_08.setText(_translate("MainWindow", "parameter8", None))
        self.label_parameter_13.setText(_translate("MainWindow", "parameter13", None))
        self.label_parameter_14.setText(_translate("MainWindow", "parameter14", None))
        self.label_parameter_12.setText(_translate("MainWindow", "parameter12", None))
        self.label_parameter_16.setText(_translate("MainWindow", "parameter16", None))
        self.label_parameter_17.setText(_translate("MainWindow", "parameter17", None))
        self.checkBox_parameters_update_continuous.setText(_translate("MainWindow", "continuous", None))
        self.pushButton_parameters_update.setText(_translate("MainWindow", "update parameters", None))
        self.right_tabs.setTabText(self.right_tabs.indexOf(self.parameter_tab), _translate("MainWindow", "parameters", None))
        self.rc_fc_label_headline.setText(_translate("MainWindow", "Remote Control:   NAZE", None))
        self.rc_fc_label_throttle.setText(_translate("MainWindow", "throttle", None))
        self.rc_fc_label_yaw.setText(_translate("MainWindow", "yaw", None))
        self.rc_fc_label_pitch.setText(_translate("MainWindow", "pitch", None))
        self.rc_fc_label_roll.setText(_translate("MainWindow", "roll", None))
        self.rc_fc_label_gps_home.setText(_translate("MainWindow", "home", None))
        self.rc_fc_label_gps_3.setText(_translate("MainWindow", "pos", None))
        self.rc_fc_label_mag.setText(_translate("MainWindow", "mag", None))
        self.rc_fc_label_gps.setText(_translate("MainWindow", "gps", None))
        self.rc_fc_label_baro.setText(_translate("MainWindow", "baro", None))
        self.rc_fc_label_aux1.setText(_translate("MainWindow", "aux1", None))
        self.rc_fc_label_aux1_2.setText(_translate("MainWindow", "aux2", None))
        self.rc_fc_label_aux1_3.setText(_translate("MainWindow", "aux3", None))
        self.rc_fc_label_aux1_4.setText(_translate("MainWindow", "aux4", None))
        self.rc_fc_label_read_only.setText(_translate("MainWindow", "read only", None))
        self.right_tabs.setTabText(self.right_tabs.indexOf(self.rc_fc), _translate("MainWindow", "rc_fc", None))
        self.right_tabs.setTabText(self.right_tabs.indexOf(self.altitude_tab), _translate("MainWindow", "altitude", None))
        self.checkBox.setText(_translate("MainWindow", "activate video stream", None))
        self.right_tabs.setTabText(self.right_tabs.indexOf(self.video_tab), _translate("MainWindow", "video", None))

from pyqtgraph import PlotWidget
